version: "3.8"

services:
  mtg:
    build: .
    container_name: mtg
    restart: always
    ports:
      - "8443:8443"
    volumes:
      - ./data:/data
    environment:
      - PORT=8443
      - DOMAIN=hostupdate.vmware.com
      - HOST_IP=${HOST_IP:-}
